### ISSUE TITLE
Teensy 4.+ Support

### ISSUE THREAD

**Issue by l3ennji** [dfries/datalink_ironman#1]
Hi,
since the Teensy 3.+ boards most likely won't be available anymore, support for the Teensy 4.+ boards (or moving to a more general hardware) would be a great improvement. Unfortunately, the code isn't directly transferrable from Teensy 3.+ to 4.+ since the FTM0-Module and the kinetis.h-File do not exist anymore, and it probably has to be solved by using the QuadTimer and the ixmrt.h-File supplied for the Teensy 4.+. 
I tried figuring out what to change by searching for similar expressions or variables in both files and using the hints the compiler gave me, it'll compile, but the compiled .hex-file won't run on the board. It immediately returns to the bootloader. I most certainly did most conversion wrong and missed quite a lot, but my knowledge at this point simply doesn't suffice to go any further, except share my experience and ask for help (I gladly offer any assistence I can supply!). 
After getting stuck on converting the uc_blink.cc to work with the 4.+, I tried another repository (https://github.com/synthead/timex-datalink-arduino) as a "Hail Mary", which seems to run on the Teensy 4.+, but won't really work together with the serblink-application. It starts the sync1-sequence, the LED on the board lights up, but the countdown takes way too long (~40sec per step), and the watch won't recognize the input. 
Maybe it would be worth looking at the possibility of making this connection work, since the timex-datalink-arduino-library seems to be pretty hardware independent, and already works with a lot of other applications like the Ruby-library or the original Datalink-application (https://github.com/synthead/timex_datalink_client). I still like the setwatch-application with the datafile, though, and would love to keep it running. (Mostly, because I found a pretty neat way to implement it in the linux subsystem for windows, and wrote a little application to receive a signal from the 0-IO-Port from the Teensy to automatically trigger a data download, which I intend to use with a proximity-sensor inside a 3D-printed watchholder to trigger an automated download as soon as the watch is placed inside the holder.)

Best regards

Benny

**Comment by dfries** [comment]
It's not surprising a different microcontroller has different registers or hardware.  Unfortunately my Timex Datalink watch started to burn through batteries, or I had an unfortunate bad series of batches of batteries from online and local stores (doubt it).  Between not wearing it and not having a Teensy 4.x I'm not likely to make the changes required to support it.  Thanks for the report, I hadn't been following the interface changes for the Teensy 4.x.

**Comment by l3ennji** [comment]
Hi David,

thanks a lot for your reply.

I figured it might not be that simple, and thus had a look at some alternatives, mainly the ruby lib for the timex datalink, which offers a few more features (including broader hardware compatibility, which includes the teensy 4) and is equally easy to use. But I was very much used to my old setup using your repository, so this repository was my first goto option.
Having changed to the ruby lib now, there's no need to keep this issue alive or even update this repository, as there are more versatile options available now.
Maybe a small hint indicating that this repo might be deprecated due to the needed teensy boards being unavailable could be helpful.

On a last note, I'd like to express my sincerest gratitude and respect for your work, being the probably oldest open-source solution for those neat little devices, which are still very useful to me as my daily drivers. You have done exceptionally well, and I think this repo can retire most honorably.

All the best and thanks again,

Ben
